name: Deploy MultiDocker
on:
  push:
    branches:
      - master # check your repo, your default branch might be master!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t joshuaeroca/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true joshuaeroca/react-test npm test

      - run: docker build -t joshuaeroca/multi-client ./client
      - run: docker build -t joshuaeroca/multi-nginx ./nginx
      - run: docker build -t joshuaeroca/multi-server ./server
      - run: docker build -t joshuaeroca/multi-worker ./worker

      - run: docker push joshuaeroca/multi-client
      - run: docker push joshuaeroca/multi-nginx
      - run: docker push joshuaeroca/multi-server
      - run: docker push joshuaeroca/multi-worker

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Verify Identity
        run: aws sts get-caller-identity
      - name: Test S3 Upload
        run: |
          aws s3 cp deploy.zip s3://elasticbeanstalk-us-east-1-690167397397/test-deploy.zip

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: Multi-docker-env
          existing_bucket_name: elasticbeanstalk-us-east-1-690167397397
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
